vicinae/src/services/clipboard/wlr-clipboard-server.cpp
We don't need such specific activation checks, especially since we only have one clipboard server available for environments as of now.
May fix #14
=> feat: simplify activation logic for wlr clipboard server on wayland envs

vicinae/src/extension/manager/extension-manager.cpp
The hardcoded /bin/node path was creating packaging issues.
=> fix(extension): let QProcess infer node path

vicinae/src/main.cpp, vicinae/src/services/app-service/app-service.cpp, vicinae/src/services/app-service/xdg/xdg-app-database.cpp, vicinae/src/services/root-item-manager/root-item-manager.hpp
This PR prevents duplicate .desktop entries from loading by prioritizing according to their order in XDG_DATA_DIRS. It also adds XDG_DATA_HOME to the default search paths, and fixes additional search paths not being automatically loaded on daemon start.
Closes #33
Closes #57 
Closes #46
=> .desktop entry loading fixes

.gitignore, vicinae/src/main.cpp
fixes this compilation error:
``` [81/222] Building CXX object
vicinae/CMakeFiles/vicinae.dir/src/main.cpp.o
/home/kainoa/.cache/yay/vicinae-git/src/vicinae/vicinae/src/main.cpp: In
function ‘int startDaemon()’:
/home/kainoa/.cache/yay/vicinae-git/src/vicinae/vicinae/src/main.cpp:168:60:
warning: ‘this’ pointer is null [-Wnonnull] 168 | for (const auto
&manifest : extensionRegistry->scanAll()) { | ^ In file included from
/home/kainoa/.cache/yay/vicinae-git/src/vicinae/vicinae/include/extension/extension.hpp:5,
from
/home/kainoa/.cache/yay/vicinae-git/src/vicinae/vicinae/src/extension/manager/extension-manager.hpp:9,
from
/home/kainoa/.cache/yay/vicinae-git/src/vicinae/vicinae/src/main.cpp:46:
/home/kainoa/.cache/yay/vicinae-git/src/vicinae/vicinae/src/services/extension-registry/extension- …
```
=> fix: extension registry null pointer

vicinae/src/services/clipboard/clipboard-service.cpp
**UPDATE**
With less code I was trying to just choose the preferred mime type to show the copied text as discussed in the reactions on this merge request, which seems like the better way to do. 
I now have the following working.
<hr />
<details>
<summary>Original issue</summary>
When you now try to copy text from a firefox/zen browser window it shows up as text and not as a bunch of null characters. _See screenshot_
The selection text in the screenshot is what is being shown in the clipboard history. The output of `wl-paste` is the following 
```bash
text/html
text/_moz_htmlcontext
text/_moz_htmlinfo
text/plain;charset=utf-8
UTF8_STRING
COMPOUND_TEXT
TEXT
text/plain
STRING
text/plain;charset=utf-8
text/plain
text/x-moz-url-priv
```
I changed the priority of formats since it struggled with …
=> fix(clipboard): Choose preferred mimeType for copy selection

vicinae/src/actions/root-search/root-search-actions.cpp
implements #123 for all root search items: apps, shortcuts, no-view commands.
=> feat: always reset search text after a default root action executes

vicinae/CMakeLists.txt, vicinae/include/extend/action-model.hpp, vicinae/src/actions/extension/extension-actions.cpp, vicinae/src/actions/extension/extension-actions.hpp, vicinae/src/actions/root-search/root-search-actions.cpp, vicinae/src/actions/root-search/root-search-actions.hpp, vicinae/src/extensions/raycast/store/store-detail-view.hpp, vicinae/src/extensions/raycast/store/store-listing-view.hpp, vicinae/src/root-search/extensions/extension-root-provider.cpp, vicinae/src/root-search/extensions/extension-root-provider.hpp, vicinae/src/ui/views/base-view.cpp
Implements #154 
Extensions can now be uninstalled from the extension list and detail pages.
=> feat(extension): add uninstall action from within extension views

vicinae/src/navigation-controller.cpp
- essential for Gnome since everything is considered a window and it grabs focus.
=> Add environment variable check to conditionally show notifications

vicinae/CMakeLists.txt, vicinae/src/services/files-service/file-indexer/abstract-scanner.cpp, vicinae/src/services/files-service/file-indexer/abstract-scanner.hpp, vicinae/src/services/files-service/file-indexer/file-indexer-db.hpp, vicinae/src/services/files-service/file-indexer/file-indexer.cpp, vicinae/src/services/files-service/file-indexer/file-indexer.hpp, vicinae/src/services/files-service/file-indexer/home-directory-watcher.cpp, vicinae/src/services/files-service/file-indexer/home-directory-watcher.hpp, vicinae/src/services/files-service/file-indexer/incremental-scanner.cpp, vicinae/src/services/files-service/file-indexer/incremental-scanner.hpp, vicinae/src/services/files-service/file-indexer/indexer-scanner.cpp, vicinae/src/services/files-service/file-indexer/indexer-scanner.hpp, vicinae/src/services/files-service/file-indexer/scan-dispatcher.cpp, vicinae/src/services/files-service/file-indexer/scan-dispatcher.hpp, vicinae/src/services/files-service/file-indexer/scan.hpp, vicinae/src/services/files-service/file-indexer/writer-worker.cpp, vicinae/src/services/files-service/file-indexer/writer-worker.hpp
Create the `ScanDispatcher` class to call the appropriate scanner - currently only `IncrementalScanner` and `IndexerScanner`, but easily extensible. It also manages the threads for these scanners.
This required creating `AbstractScanner` that all scanners derive from.
(I'm not completely satisfied about how both waiting for scans and scanning is in the same class, though)
Also moved `WriterWorker`, `Scan`, and `ScanType` to separate headers.
=> refactor: Clean up file scanners

CMakeLists.txt, Makefile, cmake/Abseil.cmake, cmake/CMark.cmake, cmake/ExtensionApi.cmake, cmake/ExtensionManager.cmake, cmake/Minizip.cmake, cmake/Protobuf.cmake, extension-manager/package-lock.json, extension-manager/package.json, extension-manager/scripts/build.mjs, extension-manager/scripts/dev.mjs, extension-manager/src/index.ts, extension-manager/src/worker.tsx, scripts/vicinae-ext-dev.sh, vicinae/CMakeLists.txt, vicinae/src/extension/manager/extension-manager.cpp, vicinae/src/extension/manager/extension-manager.hpp, vicinae/src/ipc-command-handler.cpp, vicinae/src/services/shortcut/shortcut.cpp
Not as big as it may sound, but we can now hot reload the extension manager as we make modifications to it or the api package directly. Edits to proto files will still require recompilation though.
This also fixes many cmake issues with the API/Extension manager builds.
=> feat: add  internal dev mode for extension manager

vicinae/src/extension/manager/extension-manager.cpp, vicinae/src/font-service.cpp, vicinae/src/navigation-controller.cpp, vicinae/src/ui/hud/hud.cpp, vicinae/src/ui/hud/hud.hpp, vicinae/src/ui/launcher-window/launcher-window.cpp, vicinae/src/utils/environment.hpp, vicinae/src/vicinae.cpp
this prevents the HUD from stealing focus as it's no longer a window but a layer shell surface as well.
This does not fix hud stealing on Gnome environments, where disabling the HUD is still the main recommendation.
=> fix(ui): prevent hud focus stealing using wlr layer shell

vicinae.nix
This pull request updates the npm dependency hash for the extension-manager NPM package. This error was mentioned in #6
=> fix(nix): adapt npmDeps hash for extension-manager

vicinae/include/omni-command-db.hpp, vicinae/src/root-extension-manager.hpp
Extension development auto-refresh was working (rebuilding extensions), but the Vicinae launcher UI never showed the new change but after the first fix, this got solved. And after that it started showing visual corruption with overlapping text and distorted command lists when extensions were refreshed during development.
Two issues:
1.`registerRepository()` didn't emit `registryAdded` signal when replacing existing repositories, so the UI never knew to refresh
2.  `RootExtensionManager` added new providers without removing old ones, causing duplicate entries and UI corruption
**Two minimal fixes:**
1. emit `registryAdded(repository)` when replacing existing repositories
2. remove existing provider before adding new one:
Extension development workflow now works without restarting the …
=> Fix Extension Development Auto-Refresh UI

vicinae/include/omni-command-db.hpp, vicinae/src/root-extension-manager.hpp
Reverts vicinaehq/vicinae#197
This calls `removeProvider` on every provider at startup, massively increasing vicinae startup time and also wiping existing aliases and preferences for all commands.
I should have been more careful reviewing this, my bad. Working on a fix for the original issue rn.
=> Revert "Fix Extension Development Auto-Refresh UI"

.github/workflows/release.yml, .gitignore, CMakeLists.txt, Makefile, cmake/Abseil.cmake, cmake/Protobuf.cmake, cmake/QtKeychain.cmake, cmake/QtLayerShell.cmake, vicinae/CMakeLists.txt
New binary releases will have those two statically linked.
=> build: add static linking options for qt-keychain and layer-shell

vicinae/src/services/extension-boilerplate-generator/extension-boilerplate-generator.cpp, vicinae/src/utils/environment.hpp
Attempts to mitigate #212 so that `npm install` can proceed. This is no long term fix.
=> fix: fallback version to init template if invalid

.gitignore, CMakeLists.txt, vicinae/src/main.cpp, vicinae/src/vicinae.hpp
We now ship an icon theme that is installed as part of the vicinae installation process.
It is there to provide a better out of the box experience to most users and avoid situations in which we have to default on `hicolor` because figuring out what icon theme to pick is not an easy task.
=> feat: add default vicinae icon theme (papirus) for better otb exp

flake.nix, vicinae.nix
This pull request adapts the Nix derivation to read version information from the manifest.yaml in the directory.
This resolves #212 .
Turns out Nix does not have a native Yaml parsing function? So I implemented a whacky parser with `builtins.match` and a [regex](https://regex101.com/r/vgsgYY/1)
=> fix(nix): parse manifest.yaml for nix build

vicinae/src/lib/icon-theme-db/icon-theme-db.cpp, vicinae/src/services/extension-registry/extension-registry.cpp, vicinae/src/services/files-service/file-indexer/abstract-scanner.cpp, vicinae/src/services/files-service/file-indexer/filesystem-walker.cpp, vicinae/src/services/files-service/file-indexer/incremental-scanner.cpp, vicinae/src/services/files-service/file-indexer/indexer-scanner.cpp, vicinae/src/theme.cpp, vicinae/src/ui/image/image.cpp, vicinae/src/utils/utils.cpp
Should fix #239 
Funnily enough, I wasn't able to reproduce this, but I totally see how it can happen.
We also try/catch scans now, so that if such an event still occurs we at the very least do not crash the server.
=> fix: make std::filesystem calls not crash on permission errors

vicinae/src/ui/omni-list/omni-list.hpp
by using a fixed size items without an icons will get the same size as items without one
=> fix: use fixed size for list item

vicinae.nix
Using the flake and using `lib.getExe` in my Nix config I am getting this error message:
```
evaluation warning: getExe: Package vicinae does not have the meta.mainProgram attribute. We'll assume that the main program has the same name for now, but this behavior is deprecated, because it leads to surprising errors when the assumption does not hold. If the package has a main program, please set `meta.mainProgram` in its definition to make this warning go away. Otherwise, if the package does not have a main program, or if you don't control its definition, use getExe' to specify the name to the program, such as lib.getExe' foo "bar".
```
I feel like even though it's not packaged on nixpkgs (yet) it might be good practice to add this (which will also get rid of the error message).
I also …
=> Add meta section to nix derivation

api/src/api/cache.ts
This was causing issues when cache.subscribe gets passed around
=> fix(extension): cache: use arrow functions to properly capture this

vicinae/include/extension/extension-list-component.hpp, vicinae/src/extension/extension-list-component.cpp, vicinae/src/navigation-controller.cpp, vicinae/src/navigation-controller.hpp, vicinae/src/ui/top-bar/top-bar.cpp, vicinae/src/ui/views/base-view.cpp, vicinae/src/ui/views/base-view.hpp
the accessory still took space on the right of the search bar although the accessory itself wasn't being shown
=> fix: hide search accessory container instead of actual accessory

vicinae/src/services/files-service/file-indexer/db-writer.cpp, vicinae/src/services/files-service/file-indexer/db-writer.hpp, vicinae/src/services/files-service/file-indexer/file-indexer-db.cpp, vicinae/src/services/files-service/file-indexer/file-indexer-db.hpp, vicinae/src/services/files-service/file-indexer/indexer-scanner.cpp, vicinae/src/services/files-service/file-indexer/indexer-scanner.hpp, vicinae/src/services/files-service/file-indexer/scan.hpp, vicinae/src/services/files-service/file-indexer/writer-worker.cpp, vicinae/src/services/files-service/file-indexer/writer-worker.hpp
A FileEvent struct contains:
- path
- type {Modify, Delete}
- eventTime
eventTime is now written at scan time, not DB write time.
=> refactor: Handle events in terms of `FileEvent` structs

vicinae/CMakeLists.txt, vicinae/include/watcher.hpp, vicinae/src/extensions/file/file-extension.hpp, vicinae/src/services/files-service/abstract-file-indexer.hpp, vicinae/src/services/files-service/file-indexer/file-indexer.cpp, vicinae/src/services/files-service/file-indexer/file-indexer.hpp, vicinae/src/services/files-service/file-indexer/scan-dispatcher.cpp, vicinae/src/services/files-service/file-indexer/scan.hpp, vicinae/src/services/files-service/file-indexer/watcher-scanner.cpp, vicinae/src/services/files-service/file-indexer/watcher-scanner.hpp, vicinae/src/services/files-service/file-service.cpp, vicinae/src/services/files-service/file-service.hpp
Uses [e-dant/watcher](https://github.com/e-dant/watcher) to watch for changes.
Very half-baked, but I wanted to get it out first.
Stuff to work out before merge:
- How to include `watcher.hpp`: ([watcher](https://github.com/e-dant/watcher) is a header-only library)
As of now I just pasted the file, but I think there's a way to do it using some CMake magic.
- How to make this optional:
This is probably *very* buggy, so I need to make this optional.
I went to add a setting to `FileExtension`, but the code there uses `AbstractFileIndexer` - and putting a `useWatcher()` function in that abstract class just isn't pretty.
=> feat: Implement WatcherScanner

vicinae/include/clipboard-actions.hpp, vicinae/include/clipboard-history-view.hpp, vicinae/src/services/clipboard/clipboard-db.cpp, vicinae/src/services/clipboard/clipboard-db.hpp, vicinae/src/services/clipboard/clipboard-service.cpp, vicinae/src/services/clipboard/clipboard-service.hpp
Fixes #321 
This also strengthens duplicate detection to avoid the creation of noisy entries.
=> fix: make sure copied selection is always bumped to the top of the list

vicinae/src/extension/extension-command-runtime.cpp
I was building an extension and couldn't get my command arguments to show up props.arguments was always empty.
I did some digging and it looks like the C++ backend was forgetting to pack the arguments before sending them over to the Node.js manager.
🍺
=> fix(extensions): Pass command arguments to extension runtime

module.nix
This morning I ran into an error when updating my nix config, this is because, with the current workings of the module you are required to set settings, This change makes it optional.
=> fix: Don't create vicinae.json file if not declared

vicinae/src/cli/server.cpp
Hi. I'm not sure it was a regression from the latest changes. If it was, please feel free to close this PR.
After updating, I realized the `vicinae` command was not toggling the window anymore but the server still presented the following message:
This PR fixes the message by mentioning the `vicinae toggle` command to toggle the window instead of the `vicinae` command without arguments.
For reference, this is the behavior of the `vicinae` command:
(it only displays information about the CLI).
Sorry for creating a PR directly, let me know if I should have created an issue first (I didn't find any existing issue about this problem). Thanks for the great work, it's being a pleasure daily driving Vicinae here :raised_hands:
=> Fix instructions to toggle Vicinae window after starting the server

.github/workflows/release.yml, CMakeLists.txt, nix/vicinae.nix, vicinae/src/cli/cli.cpp, vicinae/src/extensions/vicinae/report-bug-command.hpp
@jaredallard @cilginc @ArjixWasTaken you may be interested into that for your from source builds.
=> build: add VICINAE_PROVENANCE flag to identify the way vicinae was built

flake.nix, nix/module.nix
The usage of `self` to refer to the flake in the home-manager module is an extension that is not part of the main home-manager module system. While it is passed in as part of the flake in flake.nix and typically works fine, it means that non-flake users cannot use the module by doing a standard `fetchTarball` of the vicinae source code, and then referring to the `/nix/module.nix` path. By running `callPackage` inline, we can avoid the need to refer to `self` and allow non-flake users to include the module directly.
For example, as a user of `npins`, I can now use this as
```nix
let
pins = import ./npins;
in
{
imports = [ "${pins.vicinae}/nix/module.nix" ];
services.vicinae.enable = true;
}
```
whereas before the `self` parameter needed by `module.nix` would have been missing.
=> nix: allow using the module in non-flake contexts
