vicinae/src/action-panel/action-panel.hpp, vicinae/src/ui/dialog/dialog.cpp, vicinae/src/ui/launcher-window/launcher-window.cpp
Positioning logic for both the action panel and the dialog was incorrect, causing them to randomly not show up.
Should fix #22
=> fix: positioning of action panel and dialogs

vicinae/src/ui/omni-tree/omni-tree.hpp
Closes https://github.com/vicinaehq/vicinae/issues/38
I don't have any experience with Qt. Please, check if I've done it right.
=> Change OmniTree header icon when it's expanded

vicinae/include/theme.hpp, vicinae/src/theme.cpp
=> chore: Added system directory for themes

CMakeLists.txt, vicinae/CMakeLists.txt, vicinae/resources.qrc.in, vicinae/src/services/clipboard/wlr/wlr-clipboard-server.cpp, vicinae/src/xdg/xdg-desktop.cpp, wlr-clip/CMakeLists.txt, wlr-clip/src/main.cpp
=> build(wlr-clip): install wlr-clip as an external binary

vicinae/include/theme.hpp, vicinae/src/theme.cpp, vicinae/src/vicinae.cpp, vicinae/src/vicinae.hpp
=> feat(theme): search all data dirs for extra themes

extra/pywal_to_json_converter.py
users can simply use this script which will make a file in XDG_CONFIG/vicinae/themes/pywal-theme.json and update with pywal colors.
it is just a simple conversion script
=> added pywal converter python script

vicinae/src/services/app-service/xdg/xdg-app-database.cpp
Requires #140 to work properly.
=> feat: Search for .desktop files recursively

vicinae/src/services/shortcut/shortcut-service.cpp, vicinae/src/services/shortcut/shortcut.cpp, vicinae/src/services/shortcut/shortcut.hpp
=> fix(shortcut): clear parts before setting a new link

vicinae/CMakeLists.txt, vicinae/src/extension/manager/extension-manager.cpp, vicinae/src/lib/pid-file/pid-file.cpp, vicinae/src/lib/pid-file/pid-file.hpp, vicinae/src/main.cpp, vicinae/src/services/clipboard/wlr/wlr-clipboard-server.cpp
=> fix: use pid files for wlr-clip/extman to prevent proc dupe

vicinae/CMakeLists.txt, vicinae/include/extend/action-model.hpp, vicinae/src/actions/app/app-actions.cpp, vicinae/src/actions/app/app-actions.hpp, vicinae/src/command-database.cpp, vicinae/src/extensions/system/run/system-run-view.hpp, vicinae/src/extensions/system/system-extension.hpp, vicinae/src/lib/program-db/program-db.cpp, vicinae/src/lib/program-db/program-db.hpp, vicinae/src/services/app-service/abstract-app-db.hpp, vicinae/src/services/app-service/app-service.cpp, vicinae/src/services/app-service/app-service.hpp, vicinae/src/services/app-service/xdg/xdg-app-database.cpp, vicinae/src/services/app-service/xdg/xdg-app-database.hpp, vicinae/src/vicinae.cpp, vicinae/src/vicinae.hpp
=> feat: add dmenu run fashioned command to run programs directly

flake.nix
This pull request replaces the previous Cachix instance with the new, official one for Vicinae. ✨
=> feat(nix): replace Cachix instance

CMakeLists.txt, vicinae/CMakeLists.txt, vicinae/include/clipboard-history-view.hpp, vicinae/include/theme.hpp, vicinae/src/calculator-history-command.hpp, vicinae/src/extensions/calculator/calculator-extension.hpp, vicinae/src/root-command.hpp, vicinae/src/services/calculator-service/abstract-calculator-backend.hpp, vicinae/src/services/calculator-service/calculator-service.cpp, vicinae/src/services/calculator-service/calculator-service.hpp, vicinae/src/services/calculator-service/qalculate/qalculate-backend.cpp, vicinae/src/services/calculator-service/qalculate/qalculate-backend.hpp, vicinae/src/services/calculator-service/soulver-core/soulver-core.cpp, vicinae/src/services/calculator-service/soulver-core/soulver-core.hpp, vicinae/src/settings/command-metadata-settings-detail.hpp, vicinae/src/settings/extension-settings.hpp, vicinae/src/theme.cpp, vicinae/src/trie.hpp
See related project: https://github.com/vicinaehq/soulver-cpp
=> feat add SoulverCore as alternative calculator backend

extra/themes/nord/light/nord_light.json
This commit corrects the file path that was mistakenly set in the previous commit.
=> fix: Nord theme icon path

api/src/api/context/navigation-provider.tsx, cmake/ExtensionApi.cmake, vicinae/src/extension/extension-navigation-controller.hpp, vicinae/src/extension/requests/ui-request-router.cpp
It simply wasn't working at all.
=> fix(extension): properly implement pop() behaviour

vicinae/src/services/files-service/file-indexer/abstract-scanner.cpp, vicinae/src/services/files-service/file-indexer/abstract-scanner.hpp, vicinae/src/services/files-service/file-indexer/file-indexer.cpp, vicinae/src/services/files-service/file-indexer/incremental-scanner.cpp, vicinae/src/services/files-service/file-indexer/incremental-scanner.hpp, vicinae/src/services/files-service/file-indexer/indexer-scanner.cpp, vicinae/src/services/files-service/file-indexer/indexer-scanner.hpp, vicinae/src/services/files-service/file-indexer/scan-dispatcher.cpp, vicinae/src/services/files-service/file-indexer/scan-dispatcher.hpp, vicinae/src/services/files-service/file-indexer/scan.hpp
Needed for further development on #207.
=> feat: Add control abilities to AbstractScanner and ScanDispatcher

api/src/api/cache.ts, extension-manager/src/index.ts, extension-manager/src/worker.tsx, proto/extensions/manager.proto, vicinae/src/extension/extension-command-runtime.cpp
Okay implementation of a disk-based LRU cache. The index could definitely be compressed further but let's call it a day.
=> feat(extension): add support for cache API

vicinae/CMakeLists.txt, vicinae/src/ui/alert/alert.cpp, vicinae/src/ui/alert/alert.hpp, vicinae/src/ui/button-base/button-base.cpp, vicinae/src/ui/button-base/button-base.hpp, vicinae/src/ui/button/button.cpp, vicinae/src/ui/button/button.hpp, vicinae/src/ui/file-picker/file-picker.cpp, vicinae/src/ui/file-picker/file-picker.hpp, vicinae/src/ui/icon-button/icon-button.cpp, vicinae/src/ui/icon-button/icon-button.hpp, vicinae/src/ui/launcher-window/launcher-window.cpp, vicinae/src/ui/oauth-view.hpp, vicinae/src/ui/shortcut-button/shortcut-button.cpp, vicinae/src/ui/shortcut-button/shortcut-button.hpp, vicinae/src/utils/layout.hpp
=> fix: hide action veil on startup

vicinae/include/clipboard-history-view.hpp, vicinae/src/services/clipboard/clipboard-server.hpp, vicinae/src/services/clipboard/clipboard-service.cpp, vicinae/src/services/clipboard/clipboard-service.hpp, vicinae/src/services/clipboard/wlr/wlr-clipboard-server.cpp, vicinae/src/services/clipboard/wlr/wlr-clipboard-server.hpp
=> feat: allow dynamic toggling of clipboard server monitoring

api/src/api/local-storage.ts, api/src/api/raycast/components/action-panel.tsx, api/src/api/raycast/index.ts, api/src/api/raycast/local-storage.ts, api/src/api/raycast/utils.ts
=> feat(extension): add support for more legacy Raycast APIs

Makefile, vicinae/CMakeLists.txt, vicinae/src/builtin-url-command.hpp, vicinae/src/command-controller.cpp, vicinae/src/command-controller.hpp, vicinae/src/command-database.cpp, vicinae/src/extensions/file/file-extension.hpp, vicinae/src/extensions/power-management/power-management-extension.cpp, vicinae/src/extensions/power-management/power-management-extension.hpp, vicinae/src/extensions/vicinae/open-about-command.hpp, vicinae/src/extensions/vicinae/open-documentation-command.cpp, vicinae/src/extensions/vicinae/refresh-apps-command.cpp, vicinae/src/extensions/vicinae/refresh-apps-command.hpp, vicinae/src/extensions/vicinae/vicinae-extension.cpp, vicinae/src/main.cpp, vicinae/src/navigation-controller.cpp, vicinae/src/navigation-controller.hpp, vicinae/src/service-registry.cpp, vicinae/src/service-registry.hpp, vicinae/src/services/power-manager/abstract-power-manager.hpp, vicinae/src/services/power-manager/power-manager.hpp, vicinae/src/services/power-manager/systemd/systemd-power-manager.cpp, vicinae/src/services/power-manager/systemd/systemd-power-manager.hpp, vicinae/src/single-view-command-context.hpp, vicinae/src/ui/alert/alert.cpp
For now, will only work on systemd-based distributions.
Fixes #317
=> feat: add power management commands (shutdown,suspend,lock...)

extension-manager/src/index.ts, proto/manager.proto, vicinae/src/extension/extension-command-runtime.cpp
Fixes problems in #299 
I hope this is okay like this. In my testing i did not have any problems beside having to rebuild the data from the support directories
=> split up support and extension path

vicinae/CMakeLists.txt, vicinae/src/actions/root-search/root-search-actions.cpp, vicinae/src/actions/root-search/root-search-actions.hpp, vicinae/src/root-search/extensions/extension-root-provider.cpp, vicinae/src/settings-controller/settings-controller.cpp, vicinae/src/settings-controller/settings-controller.hpp, vicinae/src/settings/extension-settings.hpp, vicinae/src/settings/settings-category.hpp, vicinae/src/settings/settings-window.cpp, vicinae/src/settings/settings-window.hpp, vicinae/src/ui/omni-list/omni-list.cpp, vicinae/src/ui/omni-tree/omni-tree.cpp, vicinae/src/ui/omni-tree/omni-tree.hpp
- Improved keyboard controls
- Ability to open a specific item's preferences programatically
=> feat: improve extension-settings

wlr-clip/src/app.cpp, wlr-clip/src/app.hpp, wlr-clip/src/data-device.cpp, wlr-clip/src/data-device.hpp
Might solve #358 (still has to be tested)
=> fix(clipboard): handle primary selection even if we don't use it

api/package-lock.json, api/package.json, api/src/api/components/form.tsx, extension-manager/package-lock.json, extension-manager/package.json, extension-manager/src/reconciler.ts, vicinae.nix
Upgrading to react-19 for the various performance benefits and simply to remain up to date.
React19 is fully backward compatible so there is no compatibility problem with this.
=> feat: upgrade to react 19

extension-manager/src/patch-require.ts
Fixes #354 
This seemingly affected all raycast extensions that are built using pure javascript instead of typescript.
=> fix(api): inject _jsx* factories to improve compat with plain js

lib/xdgpp/xdgpp/desktop-entry/reader.cpp, lib/xdgpp/xdgpp/env/env.cpp, lib/xdgpp/xdgpp/locale/locale.cpp, lib/xdgpp/xdgpp/locale/locale.hpp, tests/lib/xdgpp/locale.cpp, tests/lib/xdgpp/special.cpp
=> fix: use proper locale matching logic

vicinae/src/services/app-service/xdg/xdg-app-database.cpp
=> fix: ignore empty path key

lib/xdgpp/xdgpp/desktop-entry/reader.cpp, lib/xdgpp/xdgpp/desktop-entry/reader.hpp, tests/lib/xdgpp/special.cpp
=> fix(xdgpp): handle empty keys properly

vicinae/CMakeLists.txt, vicinae/src/extensions/system/browse-apps/browse-apps-view.cpp, vicinae/src/extensions/system/browse-apps/browse-apps-view.hpp, vicinae/src/extensions/system/system-extension.hpp, vicinae/src/navigation-controller.cpp, vicinae/src/ui/views/base-view.hpp, vicinae/src/ui/views/list-view.hpp
Optional command (disabled by default) to browse apps exclusively, with option to also show apps that are normally hidden from the root search.
=> feat: add browse apps command

vicinae/include/extend/image-model.hpp, vicinae/include/theme.hpp, vicinae/src/extend/color-model.cpp, vicinae/src/extend/image-model.cpp, vicinae/src/theme.cpp, vicinae/src/ui/image/url.cpp, vicinae/src/ui/list-accessory/list-accessory.cpp, vicinae/src/ui/omni-painter/omni-painter.cpp, vicinae/src/ui/omni-painter/omni-painter.hpp, vicinae/src/utils/utils.cpp, vicinae/src/utils/utils.hpp
=> feat: simplify color handling and add dynamic color

vicinae/src/services/clipboard/clipboard-service.cpp, wlr-clip/src/app.cpp, wlr-clip/src/main.cpp
=> feat(clip): exclude selections with kde password manager hint

vicinae/src/extensions/root/root-search-view.hpp, vicinae/src/services/root-item-manager/root-item-manager.cpp
=> fix: make sure disabled items are not rendered in root search

vicinae/CMakeLists.txt, vicinae/include/extend/grid-model.hpp, vicinae/include/extension/extension-grid-component.hpp, vicinae/src/extend/grid-model.cpp, vicinae/src/ui/color-box/color-box.cpp, vicinae/src/ui/color-box/color-box.hpp
=> feat: support grid color content
